max_execution_time=600
xdebug.mode=trace
display_errors=1
memory_limit=1024M

xdebug.remote_autostart=0
xdebug.remote_enable=0
xdebug.profiler_enable=0

[opcache]
opcache.enable = 1
#opcache.revalidate_freq=120
#opcache.validate_timestamps=10
opcache.max_accelerated_files=32531
opcache.memory_consumption=256
opcache.interned_strings_buffer=16

#Test preloading
#opcache.preload_user=www-data
#opcache.preload=/www/app/init.php

